from webapp_discover.php_webapp import PhpWebApp

import os
import re

RE_VERSION = re.compile("""["']PMA_VERSION["']\s*,\s*['"](\d+(\.\d+)+)['"]""")

class PhpmyadminWebApp(PhpWebApp):
    webapp_name = "PhpMyAdmin"
    webapp_files = [
        'ChangeLog',
        'LICENSE',
        'README',
        'browse_foreigners.php',
        'changelog.php',
        'chk_rel.php',
        'config.sample.inc.php',
        'db_create.php',
        'db_datadict.php',
        'db_export.php',
        'db_import.php',
        'db_operations.php',
        'db_printview.php',
        'db_qbe.php',
        'db_search.php',
        'db_sql.php',
        'db_structure.php',
        'export.php',
        'favicon.ico',
        'import.php',
        'index.php',
        'js/functions.js',
        'js/indexes.js',
        'js/keyhandler.js',
        'js/navigation.js',
        'js/querywindow.js',
        'js/server_privileges.js',
        'js/tbl_change.js',
        'libraries/Config.class.php',
        'libraries/File.class.php',
        'libraries/List.class.php',
        'libraries/List_Database.class.php',
        'libraries/StorageEngine.class.php',
        'libraries/Table.class.php',
        'libraries/Theme.class.php',
        'libraries/Theme_Manager.class.php',
        'libraries/bookmark.lib.php',
        'libraries/charset_conversion.lib.php',
        'libraries/check_user_privileges.lib.php',
        'libraries/cleanup.lib.php',
        'libraries/common.inc.php',
        'libraries/config.default.php',
        'libraries/core.lib.php',
        'libraries/db_common.inc.php',
        'libraries/db_info.inc.php',
        'libraries/db_table_exists.lib.php',
        'libraries/display_change_password.lib.php',
        'libraries/display_create_database.lib.php',
        'libraries/display_create_table.lib.php',
        'libraries/display_export.lib.php',
        'libraries/display_import.lib.php',
        'libraries/display_select_lang.lib.php',
        'libraries/engines/bdb.lib.php',
        'libraries/engines/berkeleydb.lib.php',
        'libraries/engines/binlog.lib.php',
        'libraries/engines/innobase.lib.php',
        'libraries/engines/innodb.lib.php',
        'libraries/engines/memory.lib.php',
        'libraries/engines/merge.lib.php',
        'libraries/engines/mrg_myisam.lib.php',
        'libraries/engines/myisam.lib.php',
        'libraries/engines/ndbcluster.lib.php',
        'libraries/iconv_wrapper.lib.php',
        'libraries/import.lib.php',
        'libraries/information_schema_relations.lib.php',
        'libraries/ip_allow_deny.lib.php',
        'libraries/js_escape.lib.php',
        'libraries/kanji-encoding.lib.php',
        'libraries/mult_submits.inc.php',
        'libraries/mysql_charsets.lib.php',
        'libraries/opendocument.lib.php',
        'libraries/plugin_interface.lib.php',
        'libraries/relation.lib.php',
        'libraries/relation_cleanup.lib.php',
        'libraries/sanitizing.lib.php',
        'libraries/select_lang.lib.php',
        'libraries/select_server.lib.php',
        'libraries/server_common.inc.php',
        'libraries/session.inc.php',
        'libraries/sql_query_form.lib.php',
        'libraries/sqlparser.data.php',
        'libraries/sqlparser.lib.php',
        'libraries/sqlvalidator.class.php',
        'libraries/sqlvalidator.lib.php',
        'libraries/tbl_indexes.lib.php',
        'libraries/tbl_info.inc.php',
        'libraries/tcpdf/tcpdf.php',
        'libraries/transformations.lib.php',
        'libraries/url_generating.lib.php',
        'libraries/zip.lib.php',
        'license.php',
        'navigation.php',
        'phpinfo.php',
        'phpmyadmin.css.php',
        'pmd_display_field.php',
        'pmd_general.php',
        'pmd_pdf.php',
        'pmd_relation_new.php',
        'pmd_relation_upd.php',
        'pmd_save_pos.php',
        'print.css',
        'querywindow.php',
        'server_binlog.php',
        'server_collations.php',
        'server_databases.php',
        'server_engines.php',
        'server_export.php',
        'server_import.php',
        'server_privileges.php',
        'server_sql.php',
        'server_status.php',
        'server_variables.php',
        'show_config_errors.php',
        'sql.php',
        'tbl_addfield.php',
        'tbl_change.php',
        'tbl_create.php',
        'tbl_export.php',
        'tbl_import.php',
        'tbl_indexes.php',
        'tbl_move_copy.php',
        'tbl_operations.php',
        'tbl_printview.php',
        'tbl_relation.php',
        'tbl_replace.php',
        'tbl_row_action.php',
        'tbl_select.php',
        'tbl_sql.php',
        'tbl_structure.php',
        'themes.php',
    ] # Versions 2.11 and 4.1.6

    def get_version(self,path):

        conf_path = os.path.join(path,'libraries/Config.class.php')
        if os.path.exists(conf_path):
            cont = open(conf_path).read()
            m = RE_VERSION.search(cont)
            if m is not None:
                return (m.group(1))



    pass
